# Use Python as the base image
FROM python:3.11

# Set working directory
WORKDIR /app

# Set the PYTHONPATH to /app/backend/src
ENV PYTHONPATH=/app/backend/src:$PYTHONPATH

# Copy requirements.txt and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir --index-url https://pypi.org/simple flask
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .


CMD ["python", "-m", "flask", "--app", "src/app", "run"]
